server:
  port: 8085
  servlet:
    context-path: /api


spring:
  application:
    name: escolar-geolocation
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}