create table `ALUNO`(

    ID bigint not null auto_increment primary key,

    TURNO varchar(30),
    SERIE VARCHAR(30),
    TURMA VARCHAR(30),
    NOME_DO_PAI varchar(100),
    NOME_DA_MAE VARCHAR(100),
    CONVENIO_MEDICO VARCHAR(50),
    ATIVO boolean,
    COLEGIO_ID bigint,
    RESPONSAVEL_ID bigint,
    CONTATO_ID bigint,
    ENDERECO_ID bigint,

    FOREIGN KEY (COLEGIO_ID) REFERENCES COLEGIO(ID),
    FOREIGN KEY (RESPONSAVEL_ID) REFERENCES RESPONSAVEL(ID),
    FOREIGN KEY (CONTATO_ID) REFERENCES CONTATO(ID),
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
    );

